# Generated by Django 6.0.1 on 2026-01-17 18:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_location_lat_remove_location_lon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file', models.ImageField(help_text='Загрузите изображение (макс. 10MB)', upload_to='images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp'])], verbose_name='Изображение')),
                ('thumbnail', models.ImageField(blank=True, editable=False, null=True, upload_to='thumbnails/%Y/%m/%d/', verbose_name='Превью')),
                ('width', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file', models.FileField(help_text='Загрузите видео (макс. 100MB)', upload_to='videos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'avi', 'mov', 'mkv', 'webm', 'wmv', 'flv'])], verbose_name='Видео файл')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbs/%Y/%m/%d/', verbose_name='Превью видео')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Продолжительность')),
                ('resolution', models.CharField(blank=True, max_length=20, verbose_name='Разрешение')),
                ('file_size', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Размер файла (байт)')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='MediaGallery',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.event')),
                ('images', models.ManyToManyField(blank=True, to='main.image', verbose_name='Изображения')),
                ('videos', models.ManyToManyField(blank=True, to='main.video', verbose_name='Видео')),
            ],
        ),
    ]
